permalink: /:year-:month-:day/:title/

theme: jekyll-theme-merlot

highlighter: rouge
# markdown: redcarpet
markdown: kramdown
kramdown:
    input: GFM
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false

paginate: 5
paginate_path: ":num"
baseurl: ""



title: "Chetna's Blog"
email: "chetna.git@gmail.com"
description: "Big Data Developer"
github_username:  "chetnachaudhari"
disqus_shortname: "httpchetnachaudharigithubio"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

url: "http://chetnachaudhari.github.io"
imgrepo: "http://chetnachaudhari.github.io/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"
